export const NEWCOMPONENT_ADDED = 'NEWCOMPONENT_ADDED';
export const NEWCOMPONENT_FAIL = 'NEWCOMPONENT_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
